version: '2'

services:
  app:
    image: 'golang:1.7-onbuild'
    volumes:
      - 'data:/go'
      - '$PWD:/go/src/app'
    ports:
      - '2001:80'
    command: 'go run main.go'

volumes:
  data:
    driver: 'local'