// Code generated by "stringer -type Hand hand.go"; DO NOT EDIT

package main

import "fmt"

const _Hand_name = "RockScissorsPaper"

var _Hand_index = [...]uint8{0, 4, 12, 17}

func (i Hand) String() string {
	i -= 1
	if i < 0 || i >= Hand(len(_Hand_index)-1) {
		return fmt.Sprintf("Hand(%d)", i+1)
	}
	return _Hand_name[_Hand_index[i]:_Hand_index[i+1]]
}
